archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
artifactories:
- name: lbriggs
  mode: archive
  target: "https://lbriggs.jfrog.io/artifactory/pulumi-packages/{{ .ProjectName }}/"
  username: goreleaser
builds:
- binary: pulumi-resource-awsloadbalancercontroller
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -X github.com/jaxxstorm/pulumi-awsloadbalancercontroller/provider/pkg/version.Version={{.Tag }}
  main: ./cmd/pulumi-resource-awsloadbalancercontroller/
changelog:
  skip: true
release:
  disable: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
