// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Deployment extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'awsloadbalancercontroller:index:deployment';

    /**
     * Returns true if the given object is an instance of Deployment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Deployment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Deployment.__pulumiType;
    }


    /**
     * Create a Deployment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DeploymentArgs, opts?: pulumi.ComponentResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.namespace === undefined) && !opts.urn) {
                throw new Error("Missing required property 'namespace'");
            }
            if ((!args || args.oidcIssuer === undefined) && !opts.urn) {
                throw new Error("Missing required property 'oidcIssuer'");
            }
            if ((!args || args.oidcProvider === undefined) && !opts.urn) {
                throw new Error("Missing required property 'oidcProvider'");
            }
            inputs["namespace"] = args ? args.namespace : undefined;
            inputs["oidcIssuer"] = args ? args.oidcIssuer : undefined;
            inputs["oidcProvider"] = args ? args.oidcProvider : undefined;
        } else {
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Deployment.__pulumiType, name, inputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Deployment resource.
 */
export interface DeploymentArgs {
    /**
     * The namespace to create to run the AWS Loadbalancer Controller in.
     */
    readonly namespace: string;
    /**
     * The OIDC issuer for your EKS cluster
     */
    readonly oidcIssuer: string;
    /**
     * The OIDC provider for your EKS cluster
     */
    readonly oidcProvider: string;
}
